import { GiftTier } from '../shared/schemas/gift.schema';

export interface GiftSeed {
  id: string;
  name: string;
  icon: string;
  order: number;
  tier: GiftTier;
  visible: boolean;
  preReserved: boolean;
  reserved: boolean;
}

export const GIFTS_SEED: GiftSeed[] = [
  {
    id: 'cuna-cama',
    name: 'Cuna Cama',
    icon: 'crib',
    order: 1,
    tier: 'oculto',
    visible: false,
    preReserved: true,
    reserved: true,
  },
  {
    id: 'mecedora-silla-vibradora',
    name: 'Mecedora / silla vibradora',
    icon: 'rocking-chair',
    order: 2,
    tier: 'costoso',
    visible: true,
    preReserved: false,
    reserved: false,
  },
  {
    id: 'monitor-seguridad',
    name: 'Monitor de seguridad',
    icon: 'monitor',
    order: 3,
    tier: 'costoso',
    visible: true,
    preReserved: false,
    reserved: false,
  },
  {
    id: 'panalera-cambiador',
    name: 'Pañalera cambiador',
    icon: 'diaper-bag',
    order: 4,
    tier: 'costoso',
    visible: true,
    preReserved: false,
    reserved: false,
  },
  {
    id: 'colchon-antirreflujo',
    name: 'Colchón antirreflujo',
    icon: 'mattress',
    order: 5,
    tier: 'costoso',
    visible: true,
    preReserved: false,
    reserved: false,
  },
  {
    id: 'esterilizador-tetero',
    name: 'Esterilizador de tetero',
    icon: 'sterilizer',
    order: 6,
    tier: 'costoso',
    visible: true,
    preReserved: false,
    reserved: false,
  },
  {
    id: 'olla-hervidora',
    name: 'Olla hervidora',
    icon: 'kettle',
    order: 7,
    tier: 'costoso',
    visible: true,
    preReserved: false,
    reserved: false,
  },
  {
    id: 'kit-aseo-semanario',
    name: 'Kit de Aseo + semanario',
    icon: 'toiletries',
    order: 8,
    tier: 'economico',
    visible: true,
    preReserved: false,
    reserved: false,
  },
  {
    id: 'cobija',
    name: 'Cobija',
    icon: 'blanket',
    order: 9,
    tier: 'economico',
    visible: true,
    preReserved: false,
    reserved: false,
  },
  {
    id: 'termo',
    name: 'Termo',
    icon: 'thermos',
    order: 10,
    tier: 'economico',
    visible: true,
    preReserved: false,
    reserved: false,
  },
  {
    id: 'lampara-baja-intensidad',
    name: 'Lámpara baja intensidad',
    icon: 'lamp',
    order: 11,
    tier: 'economico',
    visible: true,
    preReserved: false,
    reserved: false,
  },
  {
    id: 'abanico-recargable',
    name: 'Abanico recargable',
    icon: 'fan',
    order: 12,
    tier: 'economico',
    visible: true,
    preReserved: false,
    reserved: false,
  },
  {
    id: 'ropita-3-6-meses',
    name: 'Ropita 3-6 meses',
    icon: 'onesie',
    order: 13,
    tier: 'economico',
    visible: true,
    preReserved: false,
    reserved: false,
  },
  {
    id: 'juguetes-estimulacion',
    name: 'Juguetes estimulación',
    icon: 'rattle',
    order: 14,
    tier: 'economico',
    visible: true,
    preReserved: false,
    reserved: false,
  },
  {
    id: 'almohada-lactancia',
    name: 'Almohada lactancia',
    icon: 'nursing-pillow',
    order: 15,
    tier: 'economico',
    visible: true,
    preReserved: false,
    reserved: false,
  },
  {
    id: 'kit-bano-bebe',
    name: 'Kit baño bebé',
    icon: 'rubber-duck',
    order: 16,
    tier: 'economico',
    visible: true,
    preReserved: false,
    reserved: false,
  },
  {
    id: 'cambiador-portatil',
    name: 'Cambiador portátil',
    icon: 'changing-pad',
    order: 17,
    tier: 'costoso',
    visible: true,
    preReserved: false,
    reserved: false,
  },
];
